name: bakta
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - bakta
  - mmseqs2
  - python >=3.10,<3.12
  - pip

  # Essential bio tools
  - prodigal
  - hmmer
  - infernal
  - blast
  - diamond
  - entrez-direct
  - ncbi-amrfinderplus
  - trnascan-se
  - aragorn

  # Optional utils
  - pyrodigal
  - biopython
  - requests
  - wget
  - pyyaml
  - xopen
  - pigz
  - pbzip2


