#'''Parameters config.'''#


# --- call_orfs --- #

baktadb: ~/bin/databases/baktadb

# --- cluster_orfs --- #

mmseqs_command: easy-cluster # choose easy-cluster or easy-linclust for larger gene catalogs
genecat_cluster_percent_identity: 0.3
coverage: 0.9

# --- filter_gene_catalog --- #
min_gene_prevalence: 1
