#'''Command-line usage resource config.'''#

# --- call_orfs --- #

call_orfs_threads: 10
call_orfs_mem_mb: 40000


# --- cluster_orfs --- #

cluster_orfs_threads: 24
cluster_orfs_mem_mb: 256000


# --- filter_gene_catalog --- #

filter_gene_catalog_threads: 1
filter_gene_catalog_mem_mb: 40000


# --- index_gene_catalog --- #

index_gene_catalog_threads: 10
index_gene_catalog_mem_mb: 150000
