#'''Command-line usage resource config.'''#

# --- call_orfs --- #

call_orfs_threads: 20
call_orfs_mem_mb: 200000


# --- cluster_orfs --- #

cluster_orfs_threads: 20
cluster_orfs_mem_mb: 200000


# --- index_gene_catalog --- #

index_gene_catalog_mem_mb: 200000


# --- run_alignments --- #

run_alignments_threads: 20
run_alignments_mem_mb: 200000
